// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMCrS984GpR0RzUGpfB8krC9nErHkQ8s4',
    appId: '1:775961987042:web:1902ab40fdad9094975bbb',
    messagingSenderId: '775961987042',
    projectId: 'hothongquanlyphongtro',
    authDomain: 'hothongquanlyphongtro.firebaseapp.com',
    storageBucket: 'hothongquanlyphongtro.firebasestorage.app',
    measurementId: 'G-L2HJ8GLMPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxiaC3YxjMYGPyYeQcnYYTmP0z3WvxZxU',
    appId: '1:775961987042:android:3233a7e021cd1bb5975bbb',
    messagingSenderId: '775961987042',
    projectId: 'hothongquanlyphongtro',
    storageBucket: 'hothongquanlyphongtro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzcgXr23l8O0d18yELR4X6QfFBJb1TJT0',
    appId: '1:775961987042:ios:4d818900f4aeeabc975bbb',
    messagingSenderId: '775961987042',
    projectId: 'hothongquanlyphongtro',
    storageBucket: 'hothongquanlyphongtro.firebasestorage.app',
    iosBundleId: 'com.example.hethongquanglyphongtro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzcgXr23l8O0d18yELR4X6QfFBJb1TJT0',
    appId: '1:775961987042:ios:4d818900f4aeeabc975bbb',
    messagingSenderId: '775961987042',
    projectId: 'hothongquanlyphongtro',
    storageBucket: 'hothongquanlyphongtro.firebasestorage.app',
    iosBundleId: 'com.example.hethongquanglyphongtro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMCrS984GpR0RzUGpfB8krC9nErHkQ8s4',
    appId: '1:775961987042:web:3362ce76bb5597e5975bbb',
    messagingSenderId: '775961987042',
    projectId: 'hothongquanlyphongtro',
    authDomain: 'hothongquanlyphongtro.firebaseapp.com',
    storageBucket: 'hothongquanlyphongtro.firebasestorage.app',
    measurementId: 'G-BZ5EHLGW3E',
  );
}
